// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Visual_Learner = 0,
	Kinematic_Learner = 1,
	Crazy_Student = 2,
	Unprepared_Student = 3,
	cant_leave_yet = 4,
	success = 5,
	Kin_Vis_Learner = 6,
}
